### ISSUE TITLE
Ferdi Issue

### ISSUE THREAD

**Issue by cohoe** [cohoe/workstation#129]
```
#0  0x00007fe54b062c85 in status_icon_changes () at /lib64/libappindicator3.so.1
#1  0x00007fe567c45c7f in g_closure_invoke () at /lib64/libgobject-2.0.so.0
#2  0x00007fe567c62126 in signal_emit_unlocked_R () at /lib64/libgobject-2.0.so.0
#3  0x00007fe567c639ea in g_signal_emit_valist () at /lib64/libgobject-2.0.so.0
#4  0x00007fe567c63c03 in g_signal_emit () at /lib64/libgobject-2.0.so.0
#5  0x00007fe54b061bfa in app_indicator_set_icon_full () at /lib64/libappindicator3.so.1
#6  0x00005591b3b8170d in  ()
#7  0x0000000000000000 in  ()
```

**Comment by cohoe** [comment]
Deprecated
